apiVersion: v1
kind: Pod
metadata: 
  name: pod1
  labels:
    app: temp
spec:
      containers:
       - name: "con1"
         image: hitman001/php-mysql:v3
         volumeMounts:
          - name: vol1
            mountPath: /app
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: php-pv-claim