apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    run: web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 30006
    protocol: TCP
  selector:
    app: apache
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pv-claim
  labels:
    app: apache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi #5 GB
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: php-apache
        image: hitman001/php-mysql:v3         #docker image to host php webserver
        ports:
        - containerPort: 80
        volumeMounts:
          - name: php-persistent-storage
            mountPath: /var/www/html
      volumes:
      - name: php-persistent-storage
        persistentVolumeClaim:
          claimName: php-pv-claim        # php data is stored in pvc
